evenhub:
  rest:
    client:
      daoApiEndpoint: http://localhost:8081
      schemaApiEndpoint: http://localhost:8082
      publisherApiEndpoint: http://localhost:8083
  pubsub:
    project: local-project
    topic: event-hub-topic
